module.exports = {
  PRIMARY_COLOR: '#057CAE',
  SECONDARY_COLOR: '#057CAE',
  FONT_COLOR_PRIMARY: '#383838',
  FONT_COLOR_SECONDARY: '#6f6f6f',
  CONTAINER_PADDING: 24,
  CONTAINER_MARGIN_TOP: -10,
  USER_KEY: 'user',
  BORDER_COLOR: '#7BB500',
  BORDER_COLOR_DELETE:'#B80000',
  DELETE_COLOR_BUTTON: '#C7C7C7'
}
